### PR TITLE
README update with Maven coordinates of the library

### PR DESCRIPTION
**Pull request by almorelle**
Feel free to update the readme once the library is uploaded to Maven Central.

### CODE REVIEW

**Comment by timothyej** [comment]
Will fix this as soon as I have the time, maybe later today. Thanks :)

**Comment by almorelle** [comment]
Just in case anybody needs it, I've deployed a [1.0.0-usercontrib](https://bintray.com/almorelle/userapp-java/userapp-java/1.0.0-usercontrib/view/files/io/userapp/userapp-java/1.0.0-usercontrib) version on bintray. I hope you're not mad at me for reusing your logo as the repo avatar. :grin:

Everything is explained in the bintray repo page but something like this in your settings.xml already works (if you use maven):

```
<?xml version="1.0" encoding="UTF-8" ?>
<settings xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd'
          xmlns='http://maven.apache.org/SETTINGS/1.0.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    <profiles>
        <profile>
            <repositories>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>userapp-java-repository</id>
                    <name>userapp-java-repository</name>
                    <url>http://dl.bintray.com/almorelle/userapp-java</url>
                </repository>
            </repositories>
            <id>userapp-java-repository</id>
        </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>userapp-java-repository</activeProfile>
    </activeProfiles>
</settings>
```

Or use the repo url directly to add in your repository manager: http://dl.bintray.com/almorelle/userapp-java

**Comment by jgangemi** [comment]
any chance this is going to be resolved and the library actually pushed to maven central?

**Comment by almorelle** [comment]
Closing since this project is dead

**Pull request closed without merging**
